# Welcome to Jekyll!
#
# 이 구성 파일은 전체 블로그에 영향을 미치는 설정용이며,
# 한 번 설정하고 그 이후에는 거의 편집하지 않습니다.
# 이 파일을 자주 편집하는 경우 자주 업데이트해야 하는 데이터에는
# Jekyll's 데이터 파일 기능을 사용하는 것이 좋습니다.
#
# 기술적인 이유로 이 파일은 'bundle Exec jekyll serve'를 사용하면
# *NOT* 자동으로 다시 로드됩니다. 이 파일을 변경하면
# 서버 프로세스를 다시 시작하십시오.
#
# YAML 구문과 관련하여 도움이 필요한 경우 다음과 같은 빠른 참조가 있습니다.
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# 사이트 설정
# These are used to personalize your new site. If you look in the HTML files,
# {{ site.mail}, {{ site.email }} 등을 통해 액세스되는 것을 볼 수 있습니다.
# 원하는 모든 사용자 지정 변수를 만들 수 있으며 이러한 변수에 액세스할 수 있습니다.
# {{ site.myvariable }을(를) 통해 템플릿에 있습니다.

title: Data scientist's room
email: empcik@pusan.ac.kr
description: # 이것의 의미는 "baseurl:"까지 줄바꿈을 무시함을 의미한다.
  [Welcome to the Data Scientist's Room. I am posting blogs to deal with
technical theories and field applications.]
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jeong-daniel.github.io/"
twitter_username: Jeong_Daniel_
github_username:  Jeong-Daniel

# Build settings
theme: minima
google_analytics: [G-2GJV30P5ZP]
color-scheme: auto/light/dark
logo: /assets/img/Person.jpg
favicon: true
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/